"""initial

Revision ID: 6a4a57517060
Revises: 
Create Date: 2025-05-20 01:43:53.386342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4a57517060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('computer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computer_name', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('mac_address', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computer')
    op.drop_table('lab')
    # ### end Alembic commands ###
