version: '3.9'

services:
  web:
    build: .
    image: my-flask-app:latest
    container_name: flask_app
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8000
      FLASK_ENV: development
    volumes:
      - .:/app
    command: flask run
