# docker-compose.yml
# version: '3.9'

services:
  web:
    build: .
    image: my-flask-app:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.dev      # Uncomment for development
      #- .env.prod    # Uncomment for production
    volumes:
      - .:/app
