version: '3.9'

services:
  web:
    build: .
    image: my-flask-app:latest
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    volumes:
      - .:/app

