# version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # maps host:container port
    restart: unless-stopped
    volumes:
      - .:/app       # lets you live-edit code locally
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py  # required by `flask run`

      
